# Generated by Django 4.2.3 on 2023-07-09 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0002_alter_invoice_date'),
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Invoice',
            new_name='Transaction',
        ),
    ]
