# Generated by Django 4.2.3 on 2023-07-08 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(max_length=500)),
                ('date', models.DateTimeField()),
                ('total_quantity', models.IntegerField()),
                ('total_amount', models.IntegerField()),
            ],
        ),
    ]
